//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petrol.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Petrol.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data	km
        ///2014-01-01	159
        ///2014-01-02	82
        ///2014-01-03	108
        ///2014-01-04	149
        ///2014-01-05	118
        ///2014-01-06	99
        ///2014-01-07	67
        ///2014-01-08	152
        ///2014-01-09	84
        ///2014-01-10	144
        ///2014-01-11	16
        ///2014-01-12	124
        ///2014-01-13	65
        ///2014-01-14	101
        ///2014-01-15	19
        ///2014-01-16	31
        ///2014-01-17	109
        ///2014-01-18	40
        ///2014-01-19	70
        ///2014-01-20	34
        ///2014-01-21	111
        ///2014-01-22	125
        ///2014-01-23	76
        ///2014-01-24	125
        ///2014-01-25	23
        ///2014-01-26	93
        ///2014-01-27	111
        ///2014-01-28	52
        ///2014-01-29	65
        ///2014-01-30	120
        ///2014-01-31	113
        ///2014-02-01	110
        ///2014-02 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lpg {
            get {
                return ResourceManager.GetString("lpg", resourceCulture);
            }
        }
    }
}
